# --------------------------------------------------
# HOMOLOGY POINTS
#
# find_localmaxima : Detects local curvature maxima along 2D or 3D curves
# find_i2 : Detects i2 landmark position along each curve
# --------------------------------------------------

# --------------------------------------------------
#  Function: find_localmaxima
# --------------------------------------------------

#' Detects local curvature maxima along projected 2D or 3D curves
#'
#' @description
#' This function identifies local curvature maxima along aperture curves.
#' Curvature is computed from smooth spline derivatives either in 3D space
#' or in 2D projected shape space (lateral or frontal views). The points of
#' maximal curvature correspond to regions of strongest bending along the shell
#' aperture profile.
#'
#' The function works on already-projected coordinates generated by
#' \code{\link{project_on_plane}}, meaning local PCA computation, spatial
#' orientation and (in 2D modes) equal-spacing resampling have already been
#' applied before curvature calculation.
#'
#' @param data A nested list of projected coordinate sets produced by
#'        \code{\link{project_on_plane}}. Each specimen must contain multiple curves
#'        excluding ventral/umbilical references.
#' @param spar Numeric smoothing parameter for spline fitting
#'        (default: 0.8). Lower values detect more curvature peaks, higher values
#'        smooth out small-scale bending.
#' @param plot Logical. If `TRUE`, detected maxima are displayed over each curve
#'        using **rgl** (2D or 3D depending on `mode`).
#' @param mode Character. Defines curvature computation space:
#'        \describe{
#'          \item{`"3D"`}{curvature computed directly on projected XYZ coordinates.}
#'          \item{`"2D_lateral"`}{curvature computed after PC1–PC2 projection + uniform arc-length resampling.}
#'          \item{`"2D_frontal"`}{curvature computed after PC1–PC3 projection + uniform arc-length resampling.}
#'        }
#'
#' @details
#' For each specimen and aperture curve:
#' \enumerate{
#'   \item A parametric curve \eqn{r(t)} is defined from projected coordinates.
#'   \item Smooth splines are fitted to coordinate trajectories.
#'   \item First and second derivatives (\eqn{r'(t)}, \eqn{r''(t)}) are computed.
#'   \item Curvature is evaluated as:
#'         \itemize{
#'           \item \eqn{\kappa = (x'y'' - y'x'')/(x'^2+y'^2)^{3/2}} in 2D.
#'           \item \eqn{\kappa = ||r'(t) \times r''(t)|| / ||r'(t)||^3} in 3D.
#'         }
#'   \item Signed curvature is preserved via normal-vector orientation.
#'   \item Local maxima are detected where curvature changes concavity,
#'         i.e. \eqn{\kappa'} crosses from positive → negative.
#' }
#'
#' @return A nested list of results for each specimen and curve:
#' \itemize{
#'   \item `curvature` : numeric vector of curvature values along the curve.
#'   \item `curvature_sign` : signed curvature reflecting bending direction.
#'   \item `maxima_indices` : index positions of local curvature maxima.
#'   \item `projection` : projected coordinates used for analysis.
#' }
#'
#' @seealso \code{\link{project_on_plane}}
#' @examples
#' \dontrun{
#' # Full 3D curvature
#' res3d   <- find_localmaxima(projections, mode="3D", spar=0.6)
#'
#' # Lateral PCA view (PC1–PC2)
#' resLat  <- find_localmaxima(projections, mode="2D_lateral")
#'
#' # Frontal PCA view (PC1–PC3)
#' resFront <- find_localmaxima(projections, mode="2D_frontal")
#' }
#'
#' @seealso \code{\link{project_on_plane}}
#' @importFrom stats smooth.spline predict
#' @importFrom pracma cross
#' @importFrom rgl lines3d points3d clear3d
#' @export

find_localmaxima <- function(data,
                             spar = 0.8,
                             plot = FALSE,
                             mode = c("2D_lateral","2D_frontal","3D")) {

  mode <- match.arg(mode)
  results <- list()

  # We get all projected curves FIRST
  projected <- project_on_plane(data, mode = mode)

  # ============================================
  # LOOP THROUGH SPECIMENS
  # ============================================
  for(specimen_id in names(projected)){

    specimen_results <- list()
    specimen_curves  <- projected[[specimen_id]]

    # LOOP curves (excluding V,U automatically since projection already removed them)
    for(curve_name in names(specimen_curves)){

      coords <- specimen_curves[[curve_name]]
      t <- seq(0, 1, length.out = nrow(coords))

      # ----------------------------------------
      #       CURVATURE 2D or 3D
      # ----------------------------------------
      if(mode != "3D"){

        spline_x <- smooth.spline(t, coords[,1], spar=spar)
        spline_y <- smooth.spline(t, coords[,2], spar=spar)

        dx <- predict(spline_x, t, deriv=1)$y
        dy <- predict(spline_y, t, deriv=1)$y
        d2x <- predict(spline_x, t, deriv=2)$y
        d2y <- predict(spline_y, t, deriv=2)$y

        curvature <- abs(dx*d2y - dy*d2x) / (dx^2+dy^2)^(3/2)
        curvature_sign <- (dx*d2y - dy*d2x) / (dx^2+dy^2)^(3/2)

      } else { # -------- 3D --------

        spline_x <- smooth.spline(t, coords[,1], spar=spar)
        spline_y <- smooth.spline(t, coords[,2], spar=spar)
        spline_z <- smooth.spline(t, coords[,3], spar=spar)

        dx <- predict(spline_x, t, deriv=1)$y
        dy <- predict(spline_y, t, deriv=1)$y
        dz <- predict(spline_z, t, deriv=1)$y
        d2x <- predict(spline_x, t, deriv=2)$y
        d2y <- predict(spline_y, t, deriv=2)$y
        d2z <- predict(spline_z, t, deriv=2)$y

        T1 <- cbind(dx,dy,dz)
        T2 <- cbind(d2x,d2y,d2z)

        cross_prod <- pracma::cross(T1,T2)
        curvature <- sqrt(rowSums(cross_prod^2)) / (rowSums(T1^2)^(3/2))

        # signed curvature
        normal_vec <- cross_prod / sqrt(rowSums(cross_prod^2))
        ref_vec <- colMeans(normal_vec,na.rm=TRUE)
        sgn <- sign(rowSums(normal_vec * matrix(ref_vec,nrow(normal_vec),3,TRUE)))
        curvature_sign <- curvature * sgn
      }

      # ----------------------------------------
      #        LOCAL MAXIMA DETECTION
      # ----------------------------------------
      maxima_indices <- sort(which(diff(sign(diff(curvature))) == -2) + 1)

      if(plot){
        rgl::lines3d(coords, col="black", lwd=2)
        if(length(maxima_indices)>0)
          rgl::points3d(coords[maxima_indices,,drop=FALSE], col="red", size=10)
      }

      specimen_results[[curve_name]] <- list(
        curvature = curvature,
        curvature_sign = curvature_sign,
        maxima_indices = maxima_indices,
        projection = coords
      )
    }

    results[[specimen_id]] <- specimen_results
  }

  if(plot) clear3d()
  return(results)
}

# --------------------------------------------------
#  Function: find_i2
# --------------------------------------------------

#' Detects i2 landmark position along each curve
#'
#' @description
#' Identify the index `i2` corresponding to the main convex curvature maximum
#' along each left/right aperture curve. If no suitable maximum is found in the
#' expected interval, the midpoint of the interval is used as a fallback.
#'
#' @param results Output list from \link{find_localmaxima}, containing curvature,
#'        maxima indices, and curve coordinates for each specimen and curve.
#'
#' @return A nested list of i2 indices for each specimen and curve.
#'
#' @details
#' For each curve:
#' \itemize{
#'   \item Expected search interval for i2:
#'         \itemize{
#'           \item `"R"` curves: indices 45-110
#'           \item `"L"` curves: indices 90-160
#'         }
#'   \item If no local maxima are found in this interval, the midpoint
#'         of the interval is used instead.
#'   \item Among convex maxima (positive curvature), the one closest
#'         to the ventral reference point is selected.
#' }
#' @examples
#' \dontrun{
#'
#' # Examples with maxima in lateral projection
#' results_lat <- find_localmaxima(data = data_missingsym, mode = "2D_lateral")
#'
#' i2_list <- find_i2(results_lateral)
#' }
#'
#' @seealso \link{find_localmaxima}
#' @export

find_i2 <- function(results) {
  i2_points <- list()

  for (specimen_id in names(results)) {
    specimen_res <- results[[specimen_id]]
    specimen_i2 <- list()

    for (curve_name in names(specimen_res)) {
      curvature <- specimen_res[[curve_name]]$curvature
      maxima_indices <- specimen_res[[curve_name]]$maxima_indices
      coords <- specimen_res[[curve_name]]$projection  # projected coordinates

      # n_ldm <- length(coords)

      # Define search interval depending on side
      if (grepl("R", curve_name)) {
        min_idx <- 40
        max_idx <- 110
        ref_point <- coords[1, ]
      } else if (grepl("L", curve_name)) {
        min_idx <- 90
        max_idx <- 160
        ref_point <- coords[nrow(coords), ]
      } else {
        specimen_i2[[curve_name]] <- NA
        warning(sprintf("Specimen %s curve %s: side not recognized, i2 set to NA", specimen_id, curve_name))
        next
      }

      # Filter maxima within interval
      valid_maxima <- maxima_indices[maxima_indices >= min_idx & maxima_indices <= max_idx]

      if (length(valid_maxima) == 0) {
        # No maxima: use midpoint fallback
        i2_idx <- round((min_idx + max_idx) / 2)
        message(sprintf("\u26A0 Specimen %s curve %s: no maxima found, using midpoint index %d as fallback",
                        specimen_id, curve_name, i2_idx))
        specimen_i2[[curve_name]] <- i2_idx
        next
      }

      # Keep convex maxima only
      convex_maxima <- valid_maxima[curvature[valid_maxima] > 0]

      if (length(convex_maxima) == 0) {
        # No convex maxima: use midpoint fallback
        i2_idx <- round((min_idx + max_idx) / 2)
        message(sprintf("\u26A0 Specimen %s curve %s: no convex maxima found, using midpoint index %d as fallback",
                        specimen_id, curve_name, i2_idx))
        specimen_i2[[curve_name]] <- i2_idx
        next
      }

      # If multiple convex maxima: pick the one closest to ventral reference
      if (length(convex_maxima) == 1) {
        i2_idx <- convex_maxima
      } else {
        distances <- sapply(convex_maxima, function(i) sum((coords[i, ] - ref_point)^2))
        i2_idx <- convex_maxima[which.min(distances)]
      }

      specimen_i2[[curve_name]] <- i2_idx
    }

    i2_points[[specimen_id]] <- specimen_i2
  }

  return(i2_points)
}



# --------------------------------------------------
#  Function: view_i2
# --------------------------------------------------

#' Plot i2 landmarks on 3D specimen curves
#'
#' @description
#' Visualize the position of i2 landmarks on 3D ammonite apertures.
#' Each specimen is shown sequentially, displaying all apertural curves in black
#' and highlighting the i2 points in red.
#'
#' @param results List returned by \link{find_localmaxima}, containing
#'   per-specimen curve coordinates or other analysis outputs.
#' @param i2_points List returned by \link{find_i2}, containing i2 landmark indices
#'   for each aperture of each specimen.
#' @param data Original landmark dataset, typically of the form
#'   `list(landmarks = list(SpecimenID = list(CurveName = matrix(X, Y, Z))))`.
#'
#' @details
#' The function opens a 3D `rgl` window for each specimen.
#' All aperture curves are plotted in black (`lines3d`), and i2 landmarks are
#' displayed as large red points (`points3d`).
#' Press **Enter** in the R console to move to the next specimen.
#'
#' @importFrom rgl title3d lines3d points3d clear3d
#'
#' @examples
#' \dontrun{
#' results_lat <- find_localmaxima(data, mode = "2D_lateral")
#' i2_list <- find_i2(results_lat)
#' view_i2(results_lat, i2_list, data)
#' }
#'
#' @seealso \link{find_localmaxima} \link{find_i2}
#' @export

view_i2 <- function(results,
                    i2_points,
                    data) {
  for (specimen_id in names(results)) {
    specimen <- results[[specimen_id]]
    specimen_landmarks <- data$landmarks[[specimen_id]]

    # Initialize 3D window
    title3d(main = specimen_id)

    # Draw all curves
    for (curve_name in names(specimen_landmarks)) {
      curve <- specimen_landmarks[[curve_name]]
      if (!is.null(curve)) {
        lines3d(curve, col = "black", lwd = 2)
      }
    }

    # Draw i2 points
    specimen_i2 <- i2_points[[specimen_id]]
    for (curve_name in names(specimen_i2)) {
      i2_idx <- specimen_i2[[curve_name]]

      if (!is.na(i2_idx)) {
        curve <- specimen_landmarks[[curve_name]]
        if (!is.null(curve) && i2_idx >= 1 && i2_idx <= nrow(curve)) {
          points3d(curve[i2_idx, , drop = FALSE], col = "red", size = 10)
        }
      }
    }

    # Wait for user input before continuing
    readline(prompt = paste0("\U1F50D Check specimen ", specimen_id, ". Press [Enter] to continue..."))

    clear3d()
  }
}
